// <auto-generated />
using System;
using BlockChainPaymentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlockChainPaymentSystem.Migrations
{
    [DbContext(typeof(RequestPaymentModelContext))]
    partial class RequestPaymentModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlockChainPaymentSystem.Models.JsonModels.RequestPaymentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("fixed_rate")
                        .HasColumnType("bit");

                    b.Property<string>("ipn_callback_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("pay_amount")
                        .HasColumnType("float");

                    b.Property<string>("pay_currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price_amount")
                        .HasColumnType("float");

                    b.Property<string>("price_currency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestPaymentModel");
                });
#pragma warning restore 612, 618
        }
    }
}
